module.exports = Object.freeze({
  PLAYER_RADIUS: 20,
  PLAYER_MAX_HP: 100,
  PLAYER_SPEED: 400,

  HUT_RADIUS: 40,
  HUT_MAX_HP: 300,

  PLAYER_FIRE_COOLDOWN: 0.5,
  BULLET_RADIUS: 15,
  BULLET_SPEED: 800,
  BULLET_DAMAGE: 10,
  BULLET_RANGE: 800,

  MAP_SIZE: 3000,
  MSG_TYPES: {
    JOIN_GAME: 'join_game',
    GAME_UPDATE: 'update',
    INPUT: 'input',
    GAME_OVER: 'dead',
  },
  COLLECTION_DISTANCE: 30,
  GENERATE_COOLDOWN: 0.5,
  GOLD_RADIUS: 10,
});
