module.exports = Object.freeze({
  PLAYER_RADIUS: 20,
  PLAYER_MAX_HP: 100,
  PLAYER_SPEED: 200,
  PLAYER_REGEN_PER_SECOND: 1,
  PLAYER_REGEN_COOLDOWN: 1,

  HUT_RADIUS: 40,
  HUT_MAX_HP: 300,
  HUT_REGEN_RATE: 10,

  PLAYER_FIRE_COOLDOWN: 1,
  BULLET_RADIUS: 15,
  BULLET_SPEED: 500,
  BULLET_DAMAGE: 30,
  BULLET_RANGE: 800,

  MAP_SIZE: 3000,
  MSG_TYPES: {
    JOIN_GAME: 'join_game',
    GAME_UPDATE: 'update',
    INPUT: 'input',
    GAME_OVER: 'dead',
  },
  COLLECTION_DISTANCE: 30,
  GOLD_GENERATE_COOLDOWN: 0.5,
  MAX_MAP_GOLD: 200,
  GOLD_RADIUS: 30,
});
